### ISSUE TITLE
Python Requests Error

### ISSUE THREAD

**Issue by ssnkhan** [intezer/analyze-community-ghidra-plugin#17]
Hello, I am running Ghidra version on 9.2.1, and the latest version of the Intezer plugin. Unfortunately, when running the script on a sample, I am getting a Python requests error. Requests is definitely installed on the system.

```
intezer_analyze_gh_community.py> Running...
Whelp, something went wrong.
Traceback (most recent call last):
  File "/usr/bin/ghidra_9.2.1_PUBLIC/Ghidra/Processors/PIC/ghidra_scripts/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 26, in <module>
    import requests
ImportError: No module named requests
intezer_analyze_gh_community.py> Finished!
```

Python `sys.version`:
`'2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)\n[OpenJDK 64-Bit Server VM (Debian)]`

Is there a way to resolve this without uninstalling/reinstalling requests? The sample is `ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa`.

**Comment by ssnkhan** [comment]
Please close, this is resolved by adding `os.name == "java"` as detailed in this earlier ticket. https://github.com/intezer/analyze-community-ghidra-plugin/issues/8

**Comment by utkonos** [comment]
Greetings,

The following pull request change may help you:
https://github.com/intezer/analyze-community-ghidra-plugin/pull/20

Also, if that does not help you, the diagnostic process that I used to view how each of the conditions resolves inside Ghidra should at least show you where the problem is located:

```
>>> import os
>>> import sys
>>> (os.name == "Posix") and (("Linux") in os.uname())
False
>>> os.name == "java"
True
>>> ("Darwin") in os.uname()
True
>>> os.name == "nt" or ("windows") in java.lang.System.getProperty("os.name").lower()
False
>>> os.name
PyShadowString('java', 'posix')
>>> os.uname()
('Darwin', 'example.com', '20.6.0', 'Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64', 'x86_64')
```
