### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by port513** [intezer/analyze-community-ghidra-plugin#18]
Traceback (most recent call last):
  File "****/ghidra_scripts/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 30, in <module>
    import requests
ImportError: No module named requests

Probably because this script expect Python 2, but we are in 2021 now and almost no Linux dist comes with Python 2 so will this plugin be upgraded to Python 3 in the near future? Really don't want to downgrade to Python 2 so it would be nice if it would support both 2 and 3 if possible.

**Comment by hartescout** [comment]
I am encountering this error as well. Checked all versions of pip I have and it is there. Probably the path to module is incorrect since there are multiple versions of Python installed on my machine. That might help your issue @port513 

I will report back

**Comment by NicoleFishbein** [comment]
Check which path is used within Ghidra to get installed packages and make sure the requests package is there.
Let me know if it works for you

**Comment by micahflack** [comment]
Add this to the beginning of whatever script you're trying to run within Ghidra.

For Linux systems, something like:
```
import sys
sys.path.append('/usr/local/lib/python2.7/dist-packages')
sys.path.append('/usr/lib/python2.7/dist-packages')
````

For Windows:
```
import sys
sys.path.append("C:\Python27\Lib\site-packages")
```

This is what got the script working for me bc of how Ghidra handles packages for Jython.

**Comment by utkonos** [comment]
Greetings,

The following pull request change may help you:
https://github.com/intezer/analyze-community-ghidra-plugin/pull/20

Also, if that does not help you, the diagnostic process that I used to view how each of the conditions resolves inside Ghidra should at least show you where the problem is located:

```
>>> import os
>>> import sys
>>> (os.name == "Posix") and (("Linux") in os.uname())
False
>>> os.name == "java"
True
>>> ("Darwin") in os.uname()
True
>>> os.name == "nt" or ("windows") in java.lang.System.getProperty("os.name").lower()
False
>>> os.name
PyShadowString('java', 'posix')
>>> os.uname()
('Darwin', 'example.com', '20.6.0', 'Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64', 'x86_64')
```

**Comment by utkonos** [comment]
I have added documentation that is very specific and should solve the error `ImportError: No module named requests`.
