### ISSUE TITLE
Ghidra 10.1.1 not showing up?

### ISSUE THREAD

**Issue by CanadianJeff** [intezer/analyze-community-ghidra-plugin#23]
I added the script folder but its not showing up in the script manager

**Comment by CanadianJeff** [comment]
nvm I just shoved it into the ghidra folder itself and get some other warning

```
intezer_analyze_gh_community.py> Running...
Traceback (most recent call last):
  File "C:\Users\Jeffery\Downloads\ghidra_10.1.1_PUBLIC\Ghidra\Features\Python\ghidra_scripts\intezer_analyze_gh_community.py", line 30, in <module>
    import requests
ImportError: No module named requests
intezer_analyze_gh_community.py> Finished!
```

**Comment by CanadianJeff** [comment]
and this is just a duplicate of #18 now sigh

**Comment by utkonos** [comment]
This is not a duplicate. I am experiencing the same issue on both macOS and Linux. The Plugin Path setting is not working. The script is in the same location as always and had worked in 10.0.X and earlier. For some reason the search process for plugins in Ghidra is not finding the script properly. I am working right now to figure out what happened.

The other problem that you have with regards to requests is indeed that other issue. I am writing up a set of instructions for a documentation PR that will help everyone get past that problem.

**Comment by utkonos** [comment]
@CanadianJeff I have documented a different way to install the plugin that works in Ghidra 10.1 using the Bundle Manager. I have just made a PR to change the documentation to show how to do the install. Take a look at that PR if you need to see how to do it immediately.
