### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by TecnoLinux** [intezer/analyze-community-ghidra-plugin#3]
i did exactly as the instructions of github and it gives me this error on linux(Manjaro latest version):
intezer_analyze_gh_community.py> Finished!
intezer_analyze_gh_community.py> Running...
>>> Program Info:
>>>	crackme:
	x86:LE:64:default_gcc
	(Thu Jul 09 21:54:10 AST 2020)
	/home/user/Downloads/crackme
>>> file SHA : 99ce00634501b4da092d0ad185bdbfe78ee67e2d7c06f1415978393bd7cd8a00
>>> Start analyzing file...
Traceback (most recent call last):
  File "/home/user/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 271, in run
    helper.create_function_map(sha256)
  File "/home/user/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 229, in create_function_map
    function_map = self._get_function_map(sha256)
  File "/home/user/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 153, in _get_function_map
    result_url = self._proxy.create_plugin_report(sha256, functions_data)
  File "/home/user/analyze-community-ghidra-plugin/intezer_analyze_gh_community.py", line 91, in create_plugin_report
    print(response.status_code)
AttributeError: 'NoneType' object has no attribute 'status_code'
intezer_analyze_gh_community.py> Finished!

**Comment by davidt99** [comment]
Hi @TecnoLinux and thanks for reaching us!
You'll need to upload the file first to intezer analyze before using the plugin.

**Comment by TecnoLinux** [comment]
Hello @davidt99 thanks for the help update again the README file i will keep doing testing on the script because i set the API key via source for some reason the script is not detecting the API_KEY and i will let you know if it is on my side or script.

**Comment by davidt99** [comment]
Update the README. Keep me posted!

**Comment by TecnoLinux** [comment]
Hello there again @davidt99 nothing bad so far in my testing,but i will close this one and open another issue that it is about making this plugin cross platform.
